services:
  app:
    image: my-bookshelf-app
    networks:
      - my-bookshelf-app-network
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bookshelf
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
  db:
    image: mysql:8.0
    networks:
      - my-bookshelf-app-network
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=bookshelf
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
networks:
  my-bookshelf-app-network: